spring:
 # profiles:
  #  active: dev
  application:
    name: springboot-study
server:
  servlet:
    context-path: /zuojie
  port: 8000
management:
  endpoint :
   shutdown:
     enable: ture #最特殊的一个监控端点
  endpoints:
    exposure:
      include: "*" # 打开所有的监控点
info:
  app:
    name: springboot-study
    groupId: com.zuojie
    version: 1.0-SNAPSHOT



